description: "Dual translation of Japanese to English and Vietnamese"

prompts:
  - "prompts/translator1.txt"
  - "prompts/translator2.txt"

providers:
  - "openai:chat:gpt-4o-mini"
  - "openai:chat:gpt-4o"
  - "anthropic:messages:claude-3-haiku-20240307"
  - "anthropic:messages:claude-3-sonnet-20240229"
  - "anthropic:messages:claude-3-5-sonnet-20240620"

tests: "tests/test_cases.csv"

defaultTest:
  assert:
    - type: javascript
      value: "!output.toLowerCase().includes('the english translation')"
    - type: javascript
      value: "!output.toLowerCase().includes('here is my translation')"
    - type: javascript
      value: "!output.toLowerCase().includes('bản dịch tiếng việt')"
    - type: javascript
      value: "!output.toLowerCase().includes('đây là bản dịch')"
options:
  showLatency: true
