description: "Dual translation of Japanese to English and Vietnamese"

prompts:
  - "prompts/translator.txt"

providers:
  - "openai:chat:gpt-4o-mini"
  - "openai:chat:gpt-4o"
  - "anthropic:messages:claude-3-haiku-20240307"
  - "anthropic:messages:claude-3-sonnet-20240229"
  - "anthropic:messages:claude-3-opus-20240229"
  - "anthropic:messages:claude-3-5-sonnet-20240620"

tests:
  - vars:
      targeted_language: "English"
      japanese_sentence: "こんにちは"
  - vars:
      targeted_language: "Vietnamese"
      japanese_sentence: "こんにちは"

options:
  showLatency: true
