# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
description: "Dual translation of Japanese to English and Vietnamese"

prompts:
  - "prompts/translator.txt"

providers:
  - "openai:chat:gpt-4o-mini"
  - "openai:chat:gpt-4o"
  - "anthropic:messages:claude-3-haiku-20240307"
  - "anthropic:messages:claude-3-sonnet-20240229"
  - "anthropic:messages:claude-3-opus-20240229"
  - "anthropic:messages:claude-3-5-sonnet-20240620"

tests:
  - vars:
      targeted_language: "English"
      japanese_sentence: "こんにちは"
    assert:
      - type: equals
        value: "Hello"
  - vars:
      targeted_language: "Vietnamese"
      japanese_sentence: "こんにちは"
    assert:
      - type: equals
        value: "Xin chào"
